/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Valeria Aybar
 */
public class IntroPage extends javax.swing.JFrame {

    /**
     * Creates new form IntroPage
     */
    public IntroPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIntroLn2 = new javax.swing.JLabel();
        jLabelIntroLn3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelBackImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(797, 530));
        setPreferredSize(new java.awt.Dimension(797, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelIntroLn2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabelIntroLn2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntroLn2.setText("You are tasked to escape before its time for your execution. ");
        getContentPane().add(jLabelIntroLn2);
        jLabelIntroLn2.setBounds(150, 50, 560, 70);

        jLabelIntroLn3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabelIntroLn3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntroLn3.setText("As you look around the room you notice ...");
        getContentPane().add(jLabelIntroLn3);
        jLabelIntroLn3.setBounds(160, 110, 430, 60);

        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jButton1.setText("Next");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 350, 100, 50);

        jLabelBackImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeria Aybar\\Documents\\NetBeansProjects\\FinalProject\\RoomBackground.jpg")); // NOI18N
        getContentPane().add(jLabelBackImage);
        jLabelBackImage.setBounds(0, -40, 840, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     ReadingNote read = new ReadingNote();
       read.show ();
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelBackImage;
    private javax.swing.JLabel jLabelIntroLn2;
    private javax.swing.JLabel jLabelIntroLn3;
    // End of variables declaration//GEN-END:variables
}
