
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Valeria Aybar
 */
public class Question1 extends javax.swing.JFrame {
 
    /**
     * Creates new form Question1
     */
    
    int counter = 50;

     Timer timer = new Timer ();
    
   
    public Question1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRiddleTitle = new javax.swing.JLabel();
        jLabelQuestion = new javax.swing.JLabel();
        jTextFieldAnswer = new javax.swing.JTextField();
        jButtonQuest1Answer = new javax.swing.JButton();
        jLabelTimer = new javax.swing.JLabel();
        jLabelTimerTitle = new javax.swing.JLabel();
        jLabelInstructionLn2 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(797, 520));
        setPreferredSize(new java.awt.Dimension(797, 520));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelRiddleTitle.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabelRiddleTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRiddleTitle.setText("Riddle 1:");
        getContentPane().add(jLabelRiddleTitle);
        jLabelRiddleTitle.setBounds(80, 120, 170, 53);

        jLabelQuestion.setBackground(new java.awt.Color(0, 0, 51));
        jLabelQuestion.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabelQuestion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuestion.setText("How many sides does a circle have?");
        getContentPane().add(jLabelQuestion);
        jLabelQuestion.setBounds(140, 190, 405, 20);

        jTextFieldAnswer.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        getContentPane().add(jTextFieldAnswer);
        jTextFieldAnswer.setBounds(260, 250, 120, 40);

        jButtonQuest1Answer.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jButtonQuest1Answer.setText("Answer");
        jButtonQuest1Answer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQuest1AnswerMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonQuest1Answer);
        jButtonQuest1Answer.setBounds(305, 344, 120, 50);

        jLabelTimer.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabelTimer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTimer.setRequestFocusEnabled(false);
        jLabelTimer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelTimerComponentShown(evt);
            }
        });
        getContentPane().add(jLabelTimer);
        jLabelTimer.setBounds(640, 60, 105, 40);

        jLabelTimerTitle.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        jLabelTimerTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTimerTitle.setText("Timer:");
        getContentPane().add(jLabelTimerTitle);
        jLabelTimerTitle.setBounds(570, 60, 70, 41);

        jLabelInstructionLn2.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        jLabelInstructionLn2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionLn2.setText("For every incorrect input 5 seconds are lost.");
        getContentPane().add(jLabelInstructionLn2);
        jLabelInstructionLn2.setBounds(50, 40, 390, 15);

        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeria Aybar\\Documents\\NetBeansProjects\\FinalProject\\Circle Background.jpg")); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, -10, 800, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuest1AnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQuest1AnswerMouseClicked

        int firstAnswer = Integer.parseInt(jTextFieldAnswer.getText());
        if (firstAnswer == 2)
        {
            JOptionPane.showMessageDialog (null,"Correct!,There is the Inside and Outside.");
            timer.cancel();
            Question2 q2 = new Question2();
                q2.show ();
                dispose();
                
        }
        else
        {
            JOptionPane.showMessageDialog (null,"Wrong, Try Again.");
            counter = (counter - 5);
           
        }
    }//GEN-LAST:event_jButtonQuest1AnswerMouseClicked

    private void jLabelTimerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelTimerComponentShown
    
      
    }//GEN-LAST:event_jLabelTimerComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
       counter = 50;
        TimerTask task;
        task = new TimerTask()
        {
            @Override
            public void run()
            {
                jLabelTimer.setText (Integer.toString(counter));
                counter--;
                if (counter <= 0)
                {
                    JOptionPane.showMessageDialog (null,"Time is Up!");
                      timer.cancel();
                      YouLose lose = new YouLose();
                       lose.show ();
                       dispose();
                }
            }
        };
        timer.scheduleAtFixedRate (task, 1000,1000);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuest1Answer;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelInstructionLn2;
    private javax.swing.JLabel jLabelQuestion;
    private javax.swing.JLabel jLabelRiddleTitle;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JLabel jLabelTimerTitle;
    private javax.swing.JTextField jTextFieldAnswer;
    // End of variables declaration//GEN-END:variables

   
    
}
