/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Valeria Aybar
 */
public class YouWin extends javax.swing.JFrame {

    /**
     * Creates new form YouWin
     */
    public YouWin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelYouWinTitle = new javax.swing.JLabel();
        jLabelYouWinLn1 = new javax.swing.JLabel();
        jButtonNewGame = new javax.swing.JButton();
        jLabelYouWinLn2 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(797, 520));
        setPreferredSize(new java.awt.Dimension(797, 520));
        getContentPane().setLayout(null);

        jLabelYouWinTitle.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        jLabelYouWinTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYouWinTitle.setText("YOU ESCAPED!!");
        getContentPane().add(jLabelYouWinTitle);
        jLabelYouWinTitle.setBounds(220, 30, 430, 80);

        jLabelYouWinLn1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabelYouWinLn1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYouWinLn1.setText("The box opened and you found the key to escape your room!     ");
        getContentPane().add(jLabelYouWinLn1);
        jLabelYouWinLn1.setBounds(150, 110, 560, 50);

        jButtonNewGame.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButtonNewGame.setText("New Game");
        jButtonNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNewGameMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonNewGame);
        jButtonNewGame.setBounds(340, 430, 140, 40);

        jLabelYouWinLn2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabelYouWinLn2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYouWinLn2.setText("Thanks for playing! ");
        getContentPane().add(jLabelYouWinLn2);
        jLabelYouWinLn2.setBounds(330, 160, 220, 30);

        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valeria Aybar\\Documents\\NetBeansProjects\\FinalProject\\Win Background.jpg")); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(-10, 0, 810, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNewGameMouseClicked
            EscapeRoom er = new EscapeRoom();
                er.show ();
                dispose();
    }//GEN-LAST:event_jButtonNewGameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelYouWinLn1;
    private javax.swing.JLabel jLabelYouWinLn2;
    private javax.swing.JLabel jLabelYouWinTitle;
    // End of variables declaration//GEN-END:variables
}
